[theme]
primaryColor="#2F39BF"

[logger]
level = "error"

[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = true
enableStaticServing = true

[client]
caching = true
toolbarMode = "minimal"